* About this ansible role
This nginx ansible role aims to provide both, configuration for reverseproxies as well as the terminating server.

It enables advanced configuration scenarios, such as complex location to upstream configs, uwsgi and unix socket support as well as TLS client authentication (optionally enforcing a specific CN presented by the client). A server may listen on multiple domains, optionally redirecting to the primary domain. HTTP basic authentication may be configured on a per-server basis.

This role is currently based on debian stable.

Note: A server is one server block in the nginx config.

** Configuration Files
This role expects to be the only entity configuring nginx on the respective host. It will disable all other sites_available (those that are not configured through this role), although it will not delete any configuration or files associated.

** Letsencrypt
The role can retrieve, configure and maintain letsencrypt certificates. One certificate per server is retrieved, containing all additional_domains of that server.

If a server does not need its letsencrypt certificate anymore, this role will delete the certificate from certbot so it is not renewed. Only certificates created by this role will ever be possibly deleted.

If the domains associated with a server change, the role will acquire new certificates for the respective server.

** Example Config
#+BEGIN_SRC yaml
nginx_workers: auto
nginx_user: www-data
nginx_revproxy_sites:
  - fqdn_: site.example.com: # FQDN of primary domain (the domain this server responds on primarily)
    location_to_upstream:
      - {protocol: 'http', location: /, addrs: ['192.168.1.1:3000']}
      - {protocol: 'https', location: /mult, addrs: ['192.168.1.1:3000', '192.168.1.2:3000'], upstream_location: '/prox', additonal_options: ['proxy_set_header X-Graylog-Server-URL https://$server_name/;']}
      - {protocol: 'http', location: /asd, socket_path: '/lol/test'}
      - {protocol: 'uwsgi', location: /asd2, socket_path: '/lol/uwsgi'}
      - {protocol: 'uwsgi', location: /asd3, addrs: ['192.168.1.10:3000'], uwsgi_param_location: '/etc/nginx/specialparams'}
      - {location: /static, webroot: '/var/www/static', client_max_body_size: '100M'}
    additional_domains:
      - site2.example.com
      - site3.example.com
    redirect_to_primary: true
    port: {http: 80, https: 443}
    ssl: {enable: false, pem_path: "", key_path: ""}
    ssl_client_auth: {enable: true, ca_cert: '/etc/ssl/certs/ca.crt', force_cn: 'server.example.com'}
    letsencrypt: {enabled: false, email: 'admin@example.com'}
    hsts: {max_age: 63072000, includeSubDomains: true}
    basic_auth: {user: 'user', password: 'pass', message: 'AUTHENTICATE'}
    log: {syslog: false, access_fmt: 'combined', error_fmt: 'error'}
    error_pages:
      - { codes: ['502', '503'], location: "/usr/share/error", site: "/unavailable.html" }
#+END_SRC
** Example Minimal Config
#+BEGIN_SRC yaml
nginx_revproxy_sites:
  - fqdn_: site.example.com:
    location_to_upstream:
      - {protocol: 'http', location: /grafana, addrs: ['127.0.0.1:3000'], additional_options: ['proxy_set_header Authorization ""']}
      - {protocol: 'http', location: /prometheus, addrs: ['127.0.0.1:9090'], upstream_location: /prometheus}
    letsencrypt: {enabled: true, email: 'admin@site.com'}
#+END_SRC
** Example using listen addresses
This example enforces authentication for external connections while allowing connections without authentication on localhost.
#+BEGIN_SRC yaml
nginx_revproxy_sites:
  - fqdn_: site.example.com:
    listen: {ipv4: 192.168.10.1} # not specifying ipv6 will listen globally ([::])
    location_to_upstream:
      - {protocol: 'http', location: /grafana, addrs: ['127.0.0.1:3000'], additional_options: ['proxy_set_header Authorization ""']}
      - {protocol: 'http', location: /prometheus, addrs: ['127.0.0.1:9090'], upstream_location: /prometheus}
    letsencrypt: {enabled: true, email: 'admin@site.com'}
    basic_auth: {user: 'user', password: 'pass, message: 'AUTHENTICATE'}
    log: {syslog: true, access_fmt: 'graylog2_json' , error_fmt: 'error'}
  - fqdn_: site.example.com_: # trailing r'_+' will be stripped. This allows multiple servers with the same server name
    listen: {ipv4: 127.0.0.1, ipv6: false} # ipv6 disabled
    location_to_upstream:
      - {protocol: 'http', location: /grafana, addrs: ['127.0.0.1:3000'], additional_options: ['proxy_set_header Authorization ""']}
      - {protocol: 'http', location: /prometheus, addrs: ['127.0.0.1:9090'], upstream_location: /prometheus}
    log: {syslog: true, access_fmt: 'graylog2_json' , error_fmt: 'error'}
#+END_SRC
